name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
    - name: Check Out Repo 
      uses: actions/checkout@v4
    - name: Install pipenv
      run: pipx install pipenv
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: pipenv
    - name: Install dependencies
      run: pipenv install
    - name: Packaging
      run: |
        pipenv run build
        chmod +x ./dist/gchls
        cd ./dist
        tar zcf gchls-snapshot.tar.gz ./gchls
        mv ./gchls-snapshot.tar.gz ../
        cd ..
    - name: Upload to artifact
      uses: actions/upload-artifact@v3
      with:
        name: gchls
        path: gchls-snapshot.tar.gz
