name: Publish

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14-xlarge
    steps:
    - name: Check Out Repo 
      uses: actions/checkout@v4
    - name: Install pipenv
      run: pipx install pipenv
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: pipenv
    - name: Install dependencies
      run: pipenv install
    - name: set locale
      run: |
        sudo locale-gen ja_JP.UTF-8
        sudo update-locale LANG=ja_JP.UTF-8
    - name: prepare requirements.txt
      run: pipenv lock -r > requirements.txt
    - name: Package Application
      uses: sayyid5416/pyinstaller@v1
      with:
        python_ver: '3.11'
        spec: './gchls.spec'
        requirements: './requirements.txt'
        upload_exe_with_name: 'gchls'
