name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: macos-13
    permissions:
      contents: write
    steps:
    - name: Check Out Repo 
      uses: actions/checkout@v4
    - name: Install pipenv
      run: pipx install pipenv
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: pipenv
    - name: Install dependencies
      run: pipenv install
    - name: Packaging
      run: |
        pipenv run build
        chmod +x ./dist/gchls
        cd ./dist
        tar zcf gchls-${{ github.ref_name }}.tar.gz ./gchls
        mv ./gchls-${{ github.ref_name }}.tar.gz ../
        cd ..
    - name: Upload to artifact
      uses: actions/upload-artifact@v3
      with:
        name: gchls
        path: "gchls-*.tar.gz"
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: gchls-${{ github.ref_name }}.tar.gz
        makeLatest: true
